---
title: "Violins of HLM specific creb targets"
author: "Cat Brown"
output:
  html_notebook:
    toc: yes
    toc_float: yes
---

This notebook serves as a continuation of 260729_creb3l3_bulk_DE_figure.Rmd

# Get expression data for targets in aECs
```{r}
aECs <- subset(atlas, short_cell_type == "EnteroAnte")
target_expression <- aECs@assays$RNA$counts %>% t() %>% data.frame() %>% dplyr::select(apoa4b.2, apoa4b.2.1, apoea) %>% cbind(aECs$condition) %>% cbind(aECs$short_cell_type_cluster) %>% 
  pivot_longer(cols = c(apoa4b.2, apoa4b.2.1, apoea))
```

# Plot it
```{r, fig.width=3.5, fig.height=3.5}
target_vln <- ggplot(target_expression, aes(x = `aECs$short_cell_type_cluster`, fill = `aECs$condition`, y = `value`)) + geom_violin(scale = "width") + geom_jitter(size = 0.01, alpha = 0.1) +
  facet_wrap(~name, ncol = 1, scales = "free_y") + 
  scale_fill_manual(values = c("hotpink1", "orange", "yellow2", "lightgreen", "steelblue1", "mediumpurple1"), labels = c("Unfed", "15 min", "30 min", "1 h", "2 h", "4 h")) +
  labs(x = "Cluster", y = "Expression Counts", fill = "Condition") + 
  theme_minimal() + theme(text = element_text(size = 7), axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
                          legend.key.size = unit(0.125, "in"), strip.text = element_text(face = "bold"))
target_vln
```
```{r}
save_plot("260730_creb_target_aEC_expression_violins.svg",target_vln, base_height = 3.5, base_width = 3.5)
```
# Session info
```{r}
sessionInfo()
```







