---
title: "Fixing cell cycle figure fonts"
author: "Cat Brown"
output:
  html_notebook:
    toc: yes
    toc_float: yes
---

# Load libraries
```{r, message=FALSE}
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(tidyverse)
library(writexl)
library(readxl)
library(cowplot)
library(svglite)
library(pheatmap)
library(ggVennDiagram)
library(aplot)
library(RColorBrewer)
``` 

# Read in atlas
```{r}
atlas <- readRDS("C:/Users/cat14/OneDrive - Johns Hopkins/Farber_Lab/Basecaller contents/atlas_paper/260212_WT_atlas_v2_cell_cycle.rds")
```

# Calculate proportions of cell cycle phases
```{r}
cell_cycle_data_phase_cell_type_2_time <- atlas@meta.data %>% group_by(short_cell_type_cluster, Cell_cycle_phase, condition) %>% 
  summarise(Count = n())
```
```{r}
lvls <- unique(cell_cycle_data_phase_cell_type_2_time$short_cell_type_cluster)
cell_cycle_data_phase_cell_type_2_time$short_cell_type_cluster <- factor(cell_cycle_data_phase_cell_type_2_time$short_cell_type_cluster, levels = lvls)
```

```{r}
cell_cycle_data_phase_cell_type_2_time <- mutate(cell_cycle_data_phase_cell_type_2_time, Cond = case_when(
  condition == "t0_UF" ~ "Unfed",
  condition == "t1_15HF" ~ "15min",
  condition == "t2_30HF" ~ "30min",
  condition == "t3_60HF" ~ "1h",
  condition == "t4_120HF" ~ "2h",
  condition == "t5_240HF" ~ "4h"
))
```

```{r}
cell_cycle_data_phase_cell_type_2_time$Cond <- factor(cell_cycle_data_phase_cell_type_2_time$Cond, levels = c("Unfed", "15min", "30min", "1h", "2h", "4h"))
```

# Plot it
```{r, fig.width=6, fig.height=20}
cell_cycle_by_cell_type_2_time <- ggplot(cell_cycle_data_phase_cell_type_2_time, aes(x = short_cell_type_cluster, y = Count, fill = Cell_cycle_phase)) + 
  geom_bar(position = "fill", stat = "identity") + 
  labs(x = "Cell Type", y = "Proportion of Cells", fill = "Cell Cycle\nPhase") +
  facet_wrap(~Cond, ncol = 6) + scale_fill_manual(values = c("#fb9a99", "#1f78b4", "#33a02c")) +
  coord_flip()  +
  theme_minimal()  + theme(legend.position = "left", text = element_text(family = "sans", size = 14), legend.key.size = unit(0.125, "in"), strip.text = element_text(size = 12), panel.spacing = unit(0.1, "lines")) + 
  scale_y_continuous(breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1))
cell_cycle_by_cell_type_2_time
```
```{r}
save_plot("260827_full_cluster_by_cycling_barplot_2x.svg", cell_cycle_by_cell_type_2_time, base_height = 20, base_width = 6)
```


# Session info
```{r}
sessionInfo()
```

